apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  finalizers:
  - apps.victoriametrics.com/finalizer
  name: system
  namespace: victoria-monitoring
spec:
  arbitraryFSAccessThroughSMs: {}
  externalLabels:
    k8s_type: private
    k8s_cluster: k8sfz-gpu-prod  #your cluster name
  extraArgs:
    loggerLevel: "INFO"  # Уровень логирования: INFO, WARN, ERROR, FATAL, PANIC
    loggerFormat: "json"
    remoteWrite.basicAuth.password: DGW9DTtbuPHmhx5j
    remoteWrite.basicAuth.username: metrics
  nodeScrapeNamespaceSelector: {}
  nodeScrapeSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  probeNamespaceSelector: {}
  remoteWrite:
  - url: https://csmis.mts.ru/victoria/insert/1902592:2117359/prometheus/api/v1/write
    tlsConfig:
      insecureSkipVerify: true
  replicaCount: 1
  resources:
    limits:
      cpu: 2500m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 500Mi
  scrapeInterval: 10s
  serviceAccountName: vmoperator-system
  serviceScrapeNamespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - victoria-monitoring
          - kube-system
          - calico-system
          - calico-apiserver
  serviceScrapeSelector: {}
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
