apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: calico-felix-metrics
  namespace: victoria-monitoring
spec:
  endpoints:
  - path: /metrics
    port: metrics
    relabelConfigs:
    - action: replace
      regex: (.*)
      replacement: ${1}
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: nodename
  jobLabel: app
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      app: calico-node

