---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: etcd-proxy-server
  name: etcd-proxy-server
  namespace: victoria-monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etcd-proxy-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etcd-proxy-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: In
                values:
                - ""
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: docker.io/mwsl2paask8s/etcd-proxy-server:0.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 1
        name: etcd-proxy-server
        ports:
        - containerPort: 8888
          name: etcd-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 8888
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/pki/etcd
          name: cert-dir
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes/pki/etcd
          type: ""
        name: cert-dir
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
    service: etcd-proxy-server
  name: etcd-proxy-server
  namespace: victoria-monitoring
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: etcd-metrics
    port: 8888
    protocol: TCP
    targetPort: etcd-proxy
  selector:
    app: etcd-proxy-server
  sessionAffinity: None
  type: ClusterIP

